version: "3"
services:
    noti-serv:
        container_name: noti-serv
        restart: always
        build: .
        ports:
            - "5001:5001"
        links:
            - mongo
    mongo:
        container_name: mongo-noti
        image: mongo
        volumes:
            - mongodata:/data/db
volumes:
    mongodata:
