version: "3"
services:
    api-auth:
        container_name: api
        restart: always
        build: .
        ports:
            - "5000:5000"
        links:
            - mongo
    mongo:
        container_name: mongo-auth
        image: mongo
        volumes:
            - mongodata:/data/db
volumes:
    mongodata:
