export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const REMOVE_USER = "REMOVE_USER";

export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const MESSAGES_LOADED = "MESSAGES_LOADED";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";

export const ADD_CONTACT = "ADD_CONTACT";
export const CONTACTS_LOADED = "CONTACTS_LOADED";
export const GROUPS_LOADED = "GROUPS_LOADED";
export const CLEAR_CONTACTS = "CLEAR_CONTACTS";
export const EMPTY_GROUPS = "EMPTY_GROUPS";
export const ADD_GROUP = "ADD_GROUP";
export const CLEAR_GROUP = "CLEAR_GROUP";

export const SOCKET_JOIN_ROOM = "SOCKET_JOIN_ROOM";
export const SOCKET_LEAVE_ROOM = "SOCKET_LEAVE_ROOM";

export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";

export const ADD_MESSAGE = "ADD_MESSAGE";
